"""storyboard shot table and first frame and last frame

Revision ID: eb5ce50804c2
Revises: e7f2a9c14b3d
Create Date: 2026-07-12 11:08:05.472436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'eb5ce50804c2'
down_revision: Union[str, Sequence[str], None] = 'e7f2a9c14b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_af_editor_project_disabled_at'), table_name='af_editor_project')
    op.drop_index(op.f('ix_af_editor_project_project_id'), table_name='af_editor_project')
    op.drop_index(op.f('ix_af_editor_project_public_id'), table_name='af_editor_project')
    op.drop_index(op.f('ix_af_editor_project_sort_order'), table_name='af_editor_project')
    op.drop_index(op.f('ix_af_editor_project_user_public_id'), table_name='af_editor_project')
    op.drop_table('af_editor_project')
    op.add_column('af_storyboard_shot', sa.Column('first_frame_media_public_id', sa.String(length=36), server_default='', nullable=True))
    op.alter_column('af_storyboard_shot', 'last_frame_media_public_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.drop_index(op.f('ix_af_storyboard_shot_last_frame_media_public_id'), table_name='af_storyboard_shot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_af_storyboard_shot_last_frame_media_public_id'), 'af_storyboard_shot', ['last_frame_media_public_id'], unique=False)
    op.alter_column('af_storyboard_shot', 'last_frame_media_public_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_column('af_storyboard_shot', 'first_frame_media_public_id')
    op.create_table('af_editor_project',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('disabled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_public_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), server_default=sa.text("'剪辑工程'::character varying"), autoincrement=False, nullable=False),
    sa.Column('timeline', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=False),
    sa.Column('duration_ms', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('ratio', sa.VARCHAR(length=20), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['af_project.id'], name=op.f('af_editor_project_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('af_editor_project_pkey')),
    sa.UniqueConstraint('project_id', name=op.f('uq_af_editor_project_project'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_af_editor_project_user_public_id'), 'af_editor_project', ['user_public_id'], unique=False)
    op.create_index(op.f('ix_af_editor_project_sort_order'), 'af_editor_project', ['sort_order'], unique=False)
    op.create_index(op.f('ix_af_editor_project_public_id'), 'af_editor_project', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_editor_project_project_id'), 'af_editor_project', ['project_id'], unique=False)
    op.create_index(op.f('ix_af_editor_project_disabled_at'), 'af_editor_project', ['disabled_at'], unique=False)
    # ### end Alembic commands ###
